### ISSUE TITLE
怎么设置可以选择除了文件夹以外的所有文件类型

### ISSUE THREAD

**Issue by lishuo1213** [zzy0516alex/FileSelectorRelease#5]

**Comment by zzy0516alex** [comment]
在FileSelectorSettings中设置：
`FileSelectorSettings settings=new FileSelectorSettings();
  settings.setFileTypesToSelect(FileInfo.FileType.Unknown)`

**Comment by zzy0516alex** [comment]
暂时没有简便的方式，可用先采用上述的方式，或等我更新新的一版

**Comment by zzy0516alex** [comment]
我已经更新6.1版本，可以使用FileInfo.FileType.File表示非文件夹类型
